project:
  type: website

website:
  title: "**Alan J Averett**"
  navbar:
    background: "#FFFFFF"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      

format:
  html:
    max-width: 300%
    theme: cosmo
    css: styles.css
    toc: false



